[package]
name = "rustock-core"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
anyhow = { workspace = true }
bitcoin = "0.32.8"
hex = "0.4.3"
serde = { workspace = true }
sha2 = "0.10.9"
thiserror = { workspace = true }
